# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/after_commit_everywhere/all/after_commit_everywhere.rbi
#
# after_commit_everywhere-1.2.0

module AfterCommitEverywhere
end
class AfterCommitEverywhere::Wrap
end
class AfterCommitEverywhere::NotInTransaction < RuntimeError
end
