# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `cypress-on-rails` gem.
# Please instead update this file by running `bin/tapioca gem cypress-on-rails`.

# source://cypress-on-rails//lib/cypress-on-rails.rb#7
Cypress = CypressOnRails

# maintain backward compatibility
#
# source://cypress-on-rails//lib/cypress-on-rails.rb#6
CypressDev = CypressOnRails

# source://cypress-on-rails//lib/cypress_on_rails/version.rb#1
module CypressOnRails
  class << self
    # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#33
    def configuration; end

    # @yield [configuration]
    #
    # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#37
    def configure; end
  end
end

# source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#4
class CypressOnRails::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#10
  def initialize; end

  # Returns the value of attribute cypress_folder.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#5
  def cypress_folder; end

  # Sets the attribute cypress_folder
  #
  # @param value the value to set the attribute cypress_folder to.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#5
  def cypress_folder=(_arg0); end

  # Returns the value of attribute logger.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#8
  def logger; end

  # Sets the attribute logger
  #
  # @param value the value to set the attribute logger to.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#8
  def logger=(_arg0); end

  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#17
  def reset; end

  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#24
  def tagged_logged; end

  # Returns the value of attribute use_middleware.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#6
  def use_middleware; end

  # Sets the attribute use_middleware
  #
  # @param value the value to set the attribute use_middleware to.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#6
  def use_middleware=(_arg0); end

  # Returns the value of attribute use_middleware.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#6
  def use_middleware?; end

  # Returns the value of attribute use_vcr_middleware.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#7
  def use_vcr_middleware; end

  # Sets the attribute use_vcr_middleware
  #
  # @param value the value to set the attribute use_vcr_middleware to.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#7
  def use_vcr_middleware=(_arg0); end

  # Returns the value of attribute use_vcr_middleware.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#7
  def use_vcr_middleware?; end
end

# source://cypress-on-rails//lib/cypress_on_rails/railtie.rb#5
class CypressOnRails::Railtie < ::Rails::Railtie; end

# source://cypress-on-rails//lib/cypress_on_rails/version.rb#2
CypressOnRails::VERSION = T.let(T.unsafe(nil), String)
