# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/database_cleaner-core/all/database_cleaner-core.rbi
#
# database_cleaner-core-2.0.1

module DatabaseCleaner
end
class DatabaseCleaner::NullStrategy
end
class DatabaseCleaner::Strategy
end
class DatabaseCleaner::UnknownStrategySpecified < ArgumentError
end
class DatabaseCleaner::Cleaner
  extend Forwardable
  include Comparable
end
class DatabaseCleaner::Safeguard
end
class DatabaseCleaner::Safeguard::Error < Exception
end
class DatabaseCleaner::Safeguard::Error::RemoteDatabaseUrl < DatabaseCleaner::Safeguard::Error
end
class DatabaseCleaner::Safeguard::Error::ProductionEnv < DatabaseCleaner::Safeguard::Error
end
class DatabaseCleaner::Safeguard::Error::UrlNotAllowed < DatabaseCleaner::Safeguard::Error
end
class DatabaseCleaner::Safeguard::AllowedUrl
end
class DatabaseCleaner::Safeguard::RemoteDatabaseUrl
end
class DatabaseCleaner::Safeguard::Production
end
class DatabaseCleaner::Cleaners < Hash
end
