# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-initializer/all/dry-initializer.rbi
#
# dry-initializer-3.1.1

module Dry
end
module Dry::Initializer
  extend Dry::Initializer::DSL
end
module Dry::Initializer::UNDEFINED
end
module Dry::Initializer::DSL
end
class Dry::Initializer::Definition
end
module Dry::Initializer::Builders
end
class Dry::Initializer::Builders::Reader
end
class Dry::Initializer::Builders::Signature
end
class Dry::Initializer::Builders::Attribute
end
class Dry::Initializer::Builders::Initializer
end
class Dry::Initializer::Config
end
module Dry::Initializer::Mixin
  extend Dry::Initializer::DSL
  include Dry::Initializer
end
module Dry::Initializer::Mixin::Root
end
module Dry::Initializer::Mixin::Local
end
module Dry::Initializer::Dispatchers
  extend Dry::Initializer::Dispatchers
end
module Dry::Initializer::Dispatchers::BuildNestedType
  extend Dry::Initializer::Dispatchers::BuildNestedType
end
module Dry::Initializer::Dispatchers::CheckType
  extend Dry::Initializer::Dispatchers::CheckType
end
module Dry::Initializer::Dispatchers::PrepareDefault
  extend Dry::Initializer::Dispatchers::PrepareDefault
end
module Dry::Initializer::Dispatchers::PrepareIvar
end
module Dry::Initializer::Dispatchers::PrepareOptional
end
module Dry::Initializer::Dispatchers::PrepareReader
  extend Dry::Initializer::Dispatchers::PrepareReader
end
module Dry::Initializer::Dispatchers::PrepareSource
end
module Dry::Initializer::Dispatchers::PrepareTarget
  extend Dry::Initializer::Dispatchers::PrepareTarget
end
module Dry::Initializer::Dispatchers::UnwrapType
  extend Dry::Initializer::Dispatchers::UnwrapType
end
module Dry::Initializer::Dispatchers::WrapType
  extend Dry::Initializer::Dispatchers::WrapType
end
class Dry::Initializer::Struct
  extend Dry::Initializer
  include Anonymous_Module_46
  include Dry::Initializer::Mixin::Root
end
module Anonymous_Module_46
  extend Dry::Initializer::Mixin::Local
end
