# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-types/all/dry-types.rbi
#
# dry-types-1.5.1

module Dry
end
module Dry::Types
  extend Anonymous_Dry_Core_Deprecations_Tagged_52
  extend Anonymous_Dry_Core_Deprecations_Tagged_54
  extend Anonymous_Dry_Core_Deprecations_Tagged_57
  extend Anonymous_Module_53
  extend Anonymous_Module_55
  extend Anonymous_Module_56
  extend Dry::Core::ClassAttributes
  extend Dry::Core::ClassAttributes
  extend Dry::Core::Deprecations::Interface
  extend Dry::Core::Deprecations::Interface
  extend Dry::Core::Deprecations::Interface
  extend Dry::Core::Extensions
  include Dry::Core::Constants
end
class Dry::Types::Container
  extend Dry::Configurable
  extend Dry::Configurable::ClassMethods
  include Dry::Container::Mixin
end
module Dry::Types::Type
  extend Anonymous_Dry_Core_Deprecations_Tagged_58
  extend Dry::Core::Deprecations::Interface
end
module Anonymous_Dry_Core_Deprecations_Tagged_58
end
module Dry::Types::Printable
end
module Dry::Types::Options
end
module Dry::Types::Decorator
  include Dry::Types::Options
end
class Dry::Types::Default
  include Anonymous_Dry_Core_Equalizer_59
  include Dry::Core::Equalizer::Methods
  include Dry::Types::Builder
  include Dry::Types::Decorator
  include Dry::Types::Printable
  include Dry::Types::Type
end
class Dry::Types::Default::Callable < Dry::Types::Default
  include Anonymous_Dry_Core_Equalizer_60
  include Dry::Core::Equalizer::Methods
end
module Anonymous_Dry_Core_Equalizer_60
end
module Anonymous_Dry_Core_Equalizer_59
end
class Dry::Types::Constrained
  include Anonymous_Dry_Core_Equalizer_61
  include Dry::Core::Equalizer::Methods
  include Dry::Types::Builder
  include Dry::Types::Decorator
  include Dry::Types::Printable
  include Dry::Types::Type
end
class Dry::Types::Constrained::Coercible < Dry::Types::Constrained
end
module Anonymous_Dry_Core_Equalizer_61
end
class Dry::Types::Enum
  include Anonymous_Dry_Core_Equalizer_62
  include Dry::Core::Equalizer::Methods
  include Dry::Types::Builder
  include Dry::Types::Decorator
  include Dry::Types::Type
end
module Anonymous_Dry_Core_Equalizer_62
end
class Dry::Types::Lax
  include Anonymous_Dry_Core_Equalizer_63
  include Dry::Core::Equalizer::Methods
  include Dry::Types::Builder
  include Dry::Types::Decorator
  include Dry::Types::Printable
  include Dry::Types::Type
end
module Anonymous_Dry_Core_Equalizer_63
end
module Anonymous_Dry_Core_Deprecations_Tagged_52
end
module Anonymous_Module_53
end
module Dry::Types::Meta
end
class Dry::Types::Sum
  include Anonymous_Dry_Core_Equalizer_64
  include Dry::Core::Equalizer::Methods
  include Dry::Types::Builder
  include Dry::Types::Meta
  include Dry::Types::Options
  include Dry::Types::Printable
  include Dry::Types::Type
end
module Anonymous_Dry_Core_Equalizer_64
end
class Dry::Types::Sum::Constrained < Dry::Types::Sum
end
module Dry::Types::Builder
  include Dry::Core::Constants
end
class Dry::Types::Result
  include Anonymous_Dry_Core_Equalizer_65
  include Dry::Core::Equalizer::Methods
end
module Anonymous_Dry_Core_Equalizer_65
end
class Dry::Types::Result::Success < Dry::Types::Result
end
class Dry::Types::Result::Failure < Dry::Types::Result
  include Anonymous_Dry_Core_Equalizer_66
  include Dry::Core::Equalizer::Methods
end
module Anonymous_Dry_Core_Equalizer_66
end
class Dry::Types::FnContainer
end
class Dry::Types::Constructor < Dry::Types::Nominal
  include Anonymous_Dry_Core_Equalizer_67
  include Dry::Core::Equalizer::Methods
end
class Dry::Types::Constructor::Function
  include Anonymous_Dry_Core_Equalizer_68
  include Dry::Core::Equalizer::Methods
end
class Dry::Types::Constructor::Function::Safe < Dry::Types::Constructor::Function
end
class Dry::Types::Constructor::Function::MethodCall < Dry::Types::Constructor::Function
end
class Dry::Types::Constructor::Function::MethodCall::PublicCall < Dry::Types::Constructor::Function::MethodCall
end
class Dry::Types::Constructor::Function::MethodCall::PrivateCall < Dry::Types::Constructor::Function::MethodCall
end
class Dry::Types::Constructor::Function::MethodCall::PrivateSafeCall < Dry::Types::Constructor::Function::MethodCall::PrivateCall
end
class Dry::Types::Constructor::Function::Wrapper < Dry::Types::Constructor::Function
end
module Anonymous_Dry_Core_Equalizer_68
end
module Dry::Types::Constructor::Wrapper
end
module Anonymous_Dry_Core_Equalizer_67
end
class Dry::Types::Array < Dry::Types::Nominal
end
class Dry::Types::Array::Constructor < Dry::Types::Constructor
end
class Dry::Types::Array::Member < Dry::Types::Array
end
class Dry::Types::Hash < Dry::Types::Nominal
end
class Dry::Types::Hash::Constructor < Dry::Types::Constructor
end
class Dry::Types::Schema < Dry::Types::Hash
  include Enumerable
end
class Dry::Types::Schema::Key
  extend Anonymous_Dry_Core_Deprecations_Tagged_69
  extend Dry::Core::Deprecations::Interface
  include Anonymous_Dry_Core_Equalizer_70
  include Dry::Core::Equalizer::Methods
  include Dry::Types::Builder
  include Dry::Types::Decorator
  include Dry::Types::Printable
  include Dry::Types::Type
end
module Anonymous_Dry_Core_Deprecations_Tagged_69
end
module Anonymous_Dry_Core_Equalizer_70
end
class Dry::Types::Map < Dry::Types::Nominal
end
class Dry::Types::Nominal
  include Anonymous_Dry_Core_Equalizer_71
  include Dry::Core::Equalizer::Methods
  include Dry::Types::Builder
  include Dry::Types::Meta
  include Dry::Types::Options
  include Dry::Types::Printable
  include Dry::Types::Type
end
module Anonymous_Dry_Core_Equalizer_71
end
module Anonymous_Dry_Core_Deprecations_Tagged_54
end
module Anonymous_Module_55
end
module Dry::Types::BuilderMethods
end
class Dry::Types::Module < Module
end
module Anonymous_Module_56
end
class Dry::Types::CoercionError < StandardError
end
class Dry::Types::MultipleError < Dry::Types::CoercionError
end
class Dry::Types::SchemaError < Dry::Types::CoercionError
end
class Dry::Types::MapError < Dry::Types::CoercionError
end
class Dry::Types::SchemaKeyError < Dry::Types::CoercionError
end
class Dry::Types::MissingKeyError < Dry::Types::SchemaKeyError
end
class Dry::Types::UnknownKeysError < Dry::Types::SchemaKeyError
end
class Dry::Types::ConstraintError < Dry::Types::CoercionError
end
class Dry::Types::AnyClass < Dry::Types::Nominal
end
module Dry::Types::Coercions
  include Dry::Core::Constants
end
module Dry::Types::Coercions::Params
  extend Dry::Types::Coercions
end
module Dry::Types::Coercions::JSON
  extend Dry::Types::Coercions
end
module Anonymous_Dry_Logic_Rule_Interface_72
end
class Dry::Logic::Rule::Predicate::Predicate2Arity < Dry::Logic::Rule::Predicate
  include Anonymous_Dry_Logic_Rule_Interface_72
end
module Anonymous_Dry_Logic_Rule_Interface_73
end
class Dry::Logic::Rule::Predicate::Predicate2Arity1Curried < Dry::Logic::Rule::Predicate
  include Anonymous_Dry_Logic_Rule_Interface_73
end
class Dry::Types::Printer
end
module Anonymous_Dry_Core_Deprecations_Tagged_57
end
