# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-configurable/all/dry-configurable.rbi
#
# dry-configurable-0.14.0

module Dry
end
module Dry::Configurable
  extend Anonymous_Module_47
  extend Anonymous_Module_48
  extend Dry::Core::ClassAttributes
  include Dry::Core::Constants
end
module Anonymous_Module_47
end
module Anonymous_Module_48
end
class Dry::Configurable::Error < StandardError
end
class Dry::Configurable::AlreadyIncluded < Dry::Configurable::Error
end
class Dry::Configurable::FrozenConfig < Dry::Configurable::Error
end
class Dry::Configurable::Config
  include Anonymous_Dry_Core_Equalizer_49
  include Dry::Core::Equalizer::Methods
end
module Anonymous_Dry_Core_Equalizer_49
end
class Dry::Configurable::Setting
  include Anonymous_Dry_Core_Equalizer_50
  include Dry::Core::Equalizer::Methods
end
module Anonymous_Dry_Core_Equalizer_50
end
class Dry::Configurable::Setting::Nested < Dry::Configurable::Setting
end
class Dry::Configurable::Settings
  include Anonymous_Dry_Core_Equalizer_51
  include Dry::Core::Equalizer::Methods
  include Enumerable
end
module Anonymous_Dry_Core_Equalizer_51
end
class Dry::Configurable::Compiler
end
class Dry::Configurable::DSL
end
module Dry::Configurable::Methods
end
module Dry::Configurable::ClassMethods
  include Dry::Configurable::Methods
end
module Dry::Configurable::Initializer
end
module Dry::Configurable::InstanceMethods
  include Dry::Configurable::Methods
end
