# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dry-configurable` gem.
# Please instead update this file by running `bin/tapioca gem dry-configurable`.

# source://dry-configurable//lib/dry/configurable/constants.rb#5
module Dry
  class << self
    # source://dry-core/0.7.1/lib/dry/core/equalizer.rb#11
    def Equalizer(*keys, **options); end

    # source://dry-struct/1.4.0/lib/dry/struct.rb#33
    def Struct(attributes = T.unsafe(nil), &block); end

    # source://dry-types/1.5.1/lib/dry/types.rb#226
    def Types(*namespaces, default: T.unsafe(nil), **aliases); end
  end
end

# A simple configuration mixin
#
# @api public
# @example class-level configuration
#
#   class App
#   extend Dry::Configurable
#
#   setting :database do
#   setting :dsn, 'sqlite:memory'
#   end
#   end
#
#   App.config.database.dsn = 'jdbc:sqlite:memory'
#   App.config.database.dsn
#   # => "jdbc:sqlite:memory"
# @example instance-level configuration
#
#   class App
#   include Dry::Configurable
#
#   setting :database
#   end
#
#   production = App.new
#   production.config.database = ENV['DATABASE_URL']
#   production.finalize!
#
#   development = App.new
#   development.config.database = 'jdbc:sqlite:memory'
#   development.finalize!
#
# source://dry-configurable//lib/dry/configurable/constants.rb#9
module Dry::Configurable
  include ::Dry::Core::Constants
  extend ::Dry::Core::Constants
  extend ::Dry::Core::ClassAttributes
  include ::Dry::Configurable::InstanceMethods

  mixes_in_class_methods ::Dry::Configurable::ClassMethods

  class << self
    # @api private
    # @private
    #
    # source://dry-configurable//lib/dry/configurable.rb#48
    def extended(klass); end

    # @api private
    # @private
    # @raise [AlreadyIncluded]
    #
    # source://dry-configurable//lib/dry/configurable.rb#54
    def included(klass); end
  end
end

# @api public
#
# source://dry-configurable//lib/dry/configurable/errors.rb#9
class Dry::Configurable::AlreadyIncluded < ::Dry::Configurable::Error; end

# source://dry-configurable//lib/dry/configurable/class_methods.rb#12
module Dry::Configurable::ClassMethods
  include ::Dry::Configurable::Methods

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/class_methods.rb#82
  def __config_dsl__; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/class_methods.rb#87
  def __config_reader__; end

  # Return declared settings
  #
  # @api public
  # @return [Settings]
  #
  # source://dry-configurable//lib/dry/configurable/class_methods.rb#63
  def _settings; end

  # Return configuration
  #
  # @api public
  # @return [Config]
  #
  # source://dry-configurable//lib/dry/configurable/class_methods.rb#72
  def config; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/class_methods.rb#16
  def inherited(subclass); end

  # Add a setting to the configuration
  #
  # @api public
  # @param name [Mixed] The accessor key for the configuration value
  # @param default [Mixed] Default value for the setting
  # @param constructor [#call] Transformation given value will go through
  # @param reader [Boolean] Whether a reader accessor must be created
  # @return [Dry::Configurable::Config]
  # @yield A block can be given to add nested settings.
  #
  # source://dry-configurable//lib/dry/configurable/class_methods.rb#39
  def setting(*args, **options, &block); end

  # Return declared settings
  #
  # @api public
  # @return [Set<Symbol>]
  #
  # source://dry-configurable//lib/dry/configurable/class_methods.rb#54
  def settings; end
end

# Setting compiler used internally by the DSL
#
# @api private
#
# source://dry-configurable//lib/dry/configurable/compiler.rb#11
class Dry::Configurable::Compiler
  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/compiler.rb#12
  def call(ast); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/compiler.rb#21
  def visit(node); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/compiler.rb#33
  def visit_nested(node); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/compiler.rb#27
  def visit_setting(node); end
end

# Config exposes setting values through a convenient API
#
# @api public
#
# source://dry-configurable//lib/dry/configurable/config.rb#15
class Dry::Configurable::Config
  include ::Dry::Core::Equalizer::Methods

  # @api private
  # @return [Config] a new instance of Config
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#25
  def initialize(settings); end

  # Get config value by a key
  #
  # @api public
  # @param name [String, Symbol]
  # @raise [ArgumentError]
  # @return Config value
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#35
  def [](name); end

  # Set config value.
  # Note that finalized configs cannot be changed.
  #
  # @api public
  # @param name [String, Symbol]
  # @param value [Object]
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#47
  def []=(name, value); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#22
  def _resolved; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#19
  def _settings; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#84
  def finalize!; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#90
  def pristine; end

  # Dump config into a hash
  #
  # @api public
  # @return [Hash]
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#75
  def to_h; end

  # Update config with new values
  #
  # @api public
  # @param values [Hash] A hash with new values
  # @return [Config]
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#58
  def update(values); end

  # Dump config into a hash
  #
  # @api public
  # @return [Hash]
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#75
  def values; end

  private

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#122
  def initialize_copy(source); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#102
  def method_missing(meth, *args); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#117
  def resolve(meth); end

  # @api private
  # @return [Boolean]
  #
  # source://dry-configurable//lib/dry/configurable/config.rb#95
  def respond_to_missing?(meth, include_private = T.unsafe(nil)); end
end

# Setting DSL used by the class API
#
# @api private
#
# source://dry-configurable//lib/dry/configurable/dsl.rb#15
class Dry::Configurable::DSL
  # @api private
  # @return [DSL] a new instance of DSL
  #
  # source://dry-configurable//lib/dry/configurable/dsl.rb#25
  def initialize(&block); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/dsl.rb#22
  def ast; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/dsl.rb#19
  def compiler; end

  # Registers a new setting node and compile it into a setting object
  #
  # @api private
  # @return Setting
  # @see ClassMethods.setting
  #
  # source://dry-configurable//lib/dry/configurable/dsl.rb#36
  def setting(name, default = T.unsafe(nil), **options, &block); end

  private

  # @api private
  # @raise [ArgumentError]
  #
  # source://dry-configurable//lib/dry/configurable/dsl.rb#149
  def ensure_valid_options(options); end

  # Returns a tuple of valid and invalid options hashes derived from the options hash
  # given to the setting
  #
  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/dsl.rb#159
  def valid_and_invalid_options(options); end
end

# @api private
#
# source://dry-configurable//lib/dry/configurable/dsl.rb#16
Dry::Configurable::DSL::VALID_NAME = T.let(T.unsafe(nil), Regexp)

# source://dry-core/0.7.1/lib/dry/core/constants.rb#112
Dry::Configurable::EMPTY_ARRAY = T.let(T.unsafe(nil), Array)

# source://dry-core/0.7.1/lib/dry/core/constants.rb#112
Dry::Configurable::EMPTY_HASH = T.let(T.unsafe(nil), Hash)

# source://dry-core/0.7.1/lib/dry/core/constants.rb#112
Dry::Configurable::EMPTY_OPTS = T.let(T.unsafe(nil), Hash)

# source://dry-core/0.7.1/lib/dry/core/constants.rb#112
Dry::Configurable::EMPTY_SET = T.let(T.unsafe(nil), Set)

# source://dry-core/0.7.1/lib/dry/core/constants.rb#112
Dry::Configurable::EMPTY_STRING = T.let(T.unsafe(nil), String)

# @api public
#
# source://dry-configurable//lib/dry/configurable/errors.rb#8
class Dry::Configurable::Error < ::StandardError; end

# @api public
#
# source://dry-configurable//lib/dry/configurable/errors.rb#10
class Dry::Configurable::FrozenConfig < ::Dry::Configurable::Error; end

# source://dry-core/0.7.1/lib/dry/core/constants.rb#112
Dry::Configurable::IDENTITY = T.let(T.unsafe(nil), Proc)

# Initializer method which is prepended when `Dry::Configurable`
# is included in a class
#
# @api private
#
# source://dry-configurable//lib/dry/configurable/instance_methods.rb#12
module Dry::Configurable::Initializer
  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/instance_methods.rb#14
  def initialize(*_arg0, **_arg1); end
end

# Instance-level API when `Dry::Configurable` is included in a class
#
# @api public
#
# source://dry-configurable//lib/dry/configurable/instance_methods.rb#28
module Dry::Configurable::InstanceMethods
  include ::Dry::Configurable::Methods

  # Return object's configuration
  #
  # @api public
  # @return [Config]
  #
  # source://dry-configurable//lib/dry/configurable/instance_methods.rb#36
  def config; end

  # Finalize the config and freeze the object
  #
  # @api public
  #
  # source://dry-configurable//lib/dry/configurable/instance_methods.rb#41
  def finalize!; end

  private

  # @api public
  #
  # source://dry-configurable//lib/dry/configurable/instance_methods.rb#51
  def initialize_copy(source); end
end

# Common API for both classes and instances
#
# @api public
#
# source://dry-configurable//lib/dry/configurable/methods.rb#10
module Dry::Configurable::Methods
  # @api public
  # @raise [FrozenConfig]
  # @yield [config]
  #
  # source://dry-configurable//lib/dry/configurable/methods.rb#12
  def configure(&block); end

  # Finalize and freeze configuration
  #
  # @api public
  # @return [Dry::Configurable::Config]
  #
  # source://dry-configurable//lib/dry/configurable/methods.rb#24
  def finalize!; end
end

# source://dry-core/0.7.1/lib/dry/core/constants.rb#112
Dry::Configurable::Self = T.let(T.unsafe(nil), Proc)

# This class represents a setting and is used internally.
#
# @api private
#
# source://dry-configurable//lib/dry/configurable/setting.rb#15
class Dry::Configurable::Setting
  include ::Dry::Core::Equalizer::Methods

  # @api private
  # @return [Setting] a new instance of Setting
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#62
  def initialize(name, input: T.unsafe(nil), default: T.unsafe(nil), **options); end

  # @api private
  # @return [Boolean]
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#126
  def cloneable?; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#111
  def constructor; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#34
  def default; end

  # @api private
  # @return [Boolean]
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#91
  def evaluated?; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#31
  def input; end

  # @api private
  # @return [Boolean]
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#81
  def input_defined?; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#25
  def name; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#96
  def nested(settings); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#37
  def options; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#101
  def pristine; end

  # @api private
  # @return [Boolean]
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#116
  def reader?; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#86
  def value; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#106
  def with(new_opts); end

  # @api private
  # @return [Boolean]
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#121
  def writer?(meth); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#28
  def writer_name; end

  private

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#154
  def evaluate; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#141
  def initialize_copy(source); end

  class << self
    # @api private
    # @return [Boolean]
    #
    # source://dry-configurable//lib/dry/configurable/setting.rb#57
    def cloneable_value?(value); end
  end
end

# @api private
#
# source://dry-configurable//lib/dry/configurable/setting.rb#22
Dry::Configurable::Setting::CLONEABLE_VALUE_TYPES = T.let(T.unsafe(nil), Array)

# @api private
#
# source://dry-configurable//lib/dry/configurable/setting.rb#20
Dry::Configurable::Setting::DEFAULT_CONSTRUCTOR = T.let(T.unsafe(nil), Proc)

# Specialized Setting which includes nested settings
#
# @api private
#
# source://dry-configurable//lib/dry/configurable/setting.rb#42
class Dry::Configurable::Setting::Nested < ::Dry::Configurable::Setting
  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#51
  def constructor; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/setting.rb#46
  def pristine; end
end

# @api private
#
# source://dry-configurable//lib/dry/configurable/setting.rb#43
Dry::Configurable::Setting::Nested::CONSTRUCTOR = T.let(T.unsafe(nil), Method)

# @api private
#
# source://dry-configurable//lib/dry/configurable/setting.rb#18
Dry::Configurable::Setting::OPTIONS = T.let(T.unsafe(nil), Array)

# A settings map
#
# @api private
#
# source://dry-configurable//lib/dry/configurable/settings.rb#13
class Dry::Configurable::Settings
  include ::Dry::Core::Equalizer::Methods
  include ::Enumerable

  # @api private
  # @return [Settings] a new instance of Settings
  #
  # source://dry-configurable//lib/dry/configurable/settings.rb#22
  def initialize(elements = T.unsafe(nil)); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/settings.rb#27
  def <<(setting); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/settings.rb#33
  def [](name); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/settings.rb#48
  def each(&block); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/settings.rb#19
  def elements; end

  # @api private
  # @return [Boolean]
  #
  # source://dry-configurable//lib/dry/configurable/settings.rb#38
  def key?(name); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/settings.rb#43
  def keys; end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/settings.rb#53
  def pristine; end

  private

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/settings.rb#60
  def initialize_copy(source); end

  # @api private
  #
  # source://dry-configurable//lib/dry/configurable/settings.rb#65
  def initialize_elements(elements); end
end

# source://dry-core/0.7.1/lib/dry/core/constants.rb#112
Dry::Configurable::Undefined = T.let(T.unsafe(nil), Object)
