# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-container/all/dry-container.rbi
#
# dry-container-0.9.0

module Dry
end
class Dry::Container
  extend Dry::Configurable
  extend Dry::Configurable::ClassMethods
  include Dry::Container::Mixin
end
class Dry::Container::Error < StandardError
end
class Dry::Container::Namespace
end
class Dry::Container::Item
end
class Dry::Container::Item::Memoizable < Dry::Container::Item
end
class Dry::Container::Item::Callable < Dry::Container::Item
end
class Dry::Container::Item::Factory
end
class Dry::Container::Registry
end
class Dry::Container::Resolver
end
class Dry::Container::NamespaceDSL < SimpleDelegator
end
module Dry::Container::Mixin
end
module Dry::Container::Mixin::Initializer
end
