# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/mini_magick/all/mini_magick.rbi
#
# mini_magick-4.11.0

module MiniMagick
  extend MiniMagick::Configuration
end
module MiniMagick::VERSION
end
module MiniMagick::Utilities
end
module MiniMagick::Configuration
end
class MiniMagick::Shell
end
class MiniMagick::Tool
end
class MiniMagick::Tool::Animate < MiniMagick::Tool
end
class MiniMagick::Tool::Compare < MiniMagick::Tool
end
class MiniMagick::Tool::Composite < MiniMagick::Tool
end
class MiniMagick::Tool::Conjure < MiniMagick::Tool
end
class MiniMagick::Tool::Convert < MiniMagick::Tool
end
class MiniMagick::Tool::Display < MiniMagick::Tool
end
class MiniMagick::Tool::Identify < MiniMagick::Tool
end
class MiniMagick::Tool::Import < MiniMagick::Tool
end
class MiniMagick::Tool::Magick < MiniMagick::Tool
end
class MiniMagick::Tool::Mogrify < MiniMagick::Tool
end
class MiniMagick::Tool::MogrifyRestricted < MiniMagick::Tool::Mogrify
end
class MiniMagick::Tool::Montage < MiniMagick::Tool
end
class MiniMagick::Tool::Stream < MiniMagick::Tool
end
class MiniMagick::Image
end
class MiniMagick::Image::Info
end
class MiniMagick::Error < RuntimeError
end
class MiniMagick::Invalid < StandardError
end
