# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/parser/all/parser.rbi
#
# parser-3.1.1.0

module Parser
end
module Parser::Messages
end
module Parser::Deprecation
end
module Parser::AST
end
class Parser::AST::Node < AST::Node
end
class Parser::AST::Processor < AST::Processor
end
module Parser::Meta
end
module Parser::Source
end
class Parser::Source::Buffer
end
class Parser::Source::Range
  include Comparable
end
class Parser::Source::Comment
end
class Parser::Source::Comment::Associator
end
class Parser::Source::Rewriter
  extend Parser::Deprecation
end
class Parser::Source::Rewriter::Action
  include Comparable
end
class Parser::Source::TreeRewriter
  extend Parser::Deprecation
end
class Parser::Source::TreeRewriter::Action
end
class Parser::Source::Map
end
class Parser::Source::Map::Operator < Parser::Source::Map
end
class Parser::Source::Map::Collection < Parser::Source::Map
end
class Parser::Source::Map::Constant < Parser::Source::Map
end
class Parser::Source::Map::Variable < Parser::Source::Map
end
class Parser::Source::Map::Keyword < Parser::Source::Map
end
class Parser::Source::Map::Definition < Parser::Source::Map
end
class Parser::Source::Map::MethodDefinition < Parser::Source::Map
end
class Parser::Source::Map::Send < Parser::Source::Map
end
class Parser::Source::Map::Index < Parser::Source::Map
end
class Parser::Source::Map::Condition < Parser::Source::Map
end
class Parser::Source::Map::Ternary < Parser::Source::Map
end
class Parser::Source::Map::For < Parser::Source::Map
end
class Parser::Source::Map::RescueBody < Parser::Source::Map
end
class Parser::Source::Map::Heredoc < Parser::Source::Map
end
class Parser::Source::Map::ObjcKwarg < Parser::Source::Map
end
class Parser::SyntaxError < StandardError
end
class Parser::ClobberingError < RuntimeError
end
class Parser::Diagnostic
end
class Parser::Diagnostic::Engine
end
class Parser::StaticEnvironment
end
class Parser::Lexer
end
class Parser::Lexer::Literal
end
class Parser::Lexer::StackState
end
class Parser::Lexer::Dedenter
end
class Parser::Builders::Default
end
class Parser::Context
end
class Parser::MaxNumparamStack
end
class Parser::CurrentArgStack
end
class Parser::VariablesStack
end
class Parser::Base < Racc::Parser
end
class Parser::Rewriter < Parser::AST::Processor
  extend Parser::Deprecation
end
class Parser::TreeRewriter < Parser::AST::Processor
end
module Parser::Builders
end
class Parser::Ruby31 < Parser::Base
end
class Parser::Ruby24 < Parser::Base
end
