# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/polyfill/all/polyfill.rbi
#
# polyfill-1.9.0

module Polyfill
end
module Polyfill::InternalUtils
end
module Polyfill::V2_2
end
module Polyfill::V2_2::Enumerable
end
module Polyfill::V2_2::Kernel
end
module Polyfill::V2_2::Math
end
module Polyfill::V2_2::Math::ClassMethods
end
module Polyfill::V2_2::Prime
end
module Polyfill::V2_2::Prime::ClassMethods
end
module Polyfill::V2_2::Vector
end
module Polyfill::V2_3
end
module Polyfill::V2_3::Array
end
module Polyfill::V2_3::Hash
end
module Polyfill::V2_3::Enumerable
end
module Polyfill::V2_3::Enumerator
end
module Polyfill::V2_3::Enumerator::Lazy
end
module Polyfill::V2_3::Kernel
end
module Polyfill::V2_3::Numeric
end
module Polyfill::V2_3::String
end
module Polyfill::V2_3::String::ClassMethods
end
module Polyfill::V2_3::Struct
end
module Polyfill::V2_3::Prime
end
module Polyfill::V2_3::Prime::ClassMethods
end
module Polyfill::V2_4
end
module Polyfill::V2_4::Numeric
end
module Polyfill::V2_4::Enumerable
end
module Polyfill::Module::MezpOdW1lcmljPT5bIiNkdXAiXSwgOnZlcnNpb249PiIyLjQifQ__
end
module Polyfill::V2_4::Array
end
module Polyfill::V2_4::Comparable
end
module Polyfill::V2_4::Dir
end
module Polyfill::V2_4::Dir::ClassMethods
end
module Polyfill::V2_4::Enumerator
end
module Polyfill::V2_4::Enumerator::Lazy
end
module Polyfill::Module::MezpFbnVtZXJhYmxlPT5bIiNjaHVua193aGlsZSJdLCA6dmVyc2lvbj0_1IjIuNCJ9
end
module Polyfill::V2_4::File
end
module Polyfill::V2_4::File::ClassMethods
end
module Polyfill::V2_4::Float
end
module Polyfill::V2_4::Hash
end
module Polyfill::V2_4::Integer
end
module Polyfill::V2_4::IO
end
module Polyfill::V2_4::IO::ClassMethods
end
module Polyfill::V2_4::MatchData
end
module Polyfill::V2_4::Object
end
module Polyfill::V2_4::Regexp
end
module Polyfill::V2_4::String
end
module Polyfill::V2_4::String::ClassMethods
end
module Polyfill::V2_4::StringIO
end
module Polyfill::V2_4::StringIO::ClassMethods
end
module Polyfill::V2_4::Symbol
end
module Polyfill::V2_4::IPAddr
end
module Polyfill::V2_4::Pathname
end
module Polyfill::V2_5
end
module Polyfill::V2_5::Array
end
module Polyfill::V2_5::Dir
end
module Polyfill::V2_5::Dir::ClassMethods
end
module Polyfill::V2_5::Enumerable
end
module Polyfill::V2_5::Hash
end
module Polyfill::V2_5::Integer
end
module Polyfill::Module::MezpJbnRlZ2VyPT5bIiNjZWlsIiwgIiNmbG9vciIsICIjcm91bmQiLCAiI3RydW5jYXRlIl0sIDp2ZXJzaW9uPT4iMi40In0_
end
module Polyfill::V2_5::Integer::ClassMethods
end
module Polyfill::V2_5::Kernel
end
module Polyfill::V2_5::String
end
module Polyfill::V2_5::Struct
end
module Polyfill::V2_5::Struct::ClassMethods
end
module Polyfill::V2_5::Time
end
module Polyfill::V2_5::Time::ClassMethods
end
module Polyfill::V2_5::BigDecimal
end
module Polyfill::V2_5::Set
end
module Polyfill::V2_6
end
module Polyfill::V2_6::Array
end
module Polyfill::V2_6::Enumerable
end
module Polyfill::V2_6::Hash
end
module Polyfill::V2_6::Kernel
end
module Polyfill::Module::MezpLZXJuZWw9PlsiI3lpZWxkX3NlbGYiXSwgOnZlcnNpb249PiIyLjUifQ__
end
module Polyfill::V2_6::OpenStruct
end
module Polyfill::V2_6::String
end
module Polyfill::V2_6::Struct
end
module Polyfill::Module
end
