# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pry/all/pry.rbi
#
# pry-0.14.1

class Pry
  extend Pry::Forwardable
end
class Pry::LastException < BasicObject
end
module Pry::Forwardable
  include Forwardable
end
module Pry::Helpers
end
module Pry::Helpers::BaseHelpers
  extend Pry::Helpers::BaseHelpers
end
module Pry::Helpers::DocumentationHelpers
end
module Pry::Helpers::OptionsHelpers
end
module Pry::Helpers::CommandHelpers
  extend Pry::Helpers::CommandHelpers
  include Pry::Helpers::OptionsHelpers
end
module Pry::Helpers::Text
  extend Pry::Helpers::Text
end
class Pry::Helpers::Table
end
module Pry::Helpers::Platform
end
class Pry::BasicObject < BasicObject
  include Kernel
end
class Pry::Prompt
end
class Pry::CodeObject
  include Pry::Helpers::CommandHelpers
end
module Pry::CodeObject::Helpers
end
module Pry::RescuableException
end
module Pry::TooSafeException
end
module Pry::UserError
end
module Pry::FrozenObjectException
end
class Pry::CommandError < StandardError
end
class Pry::MethodNotFound < Pry::CommandError
end
class Pry::ObsoleteError < StandardError
end
class Pry::Hooks
end
class Pry::InputCompleter
end
class Pry::Command
  extend Pry::CodeObject::Helpers
  extend Pry::Helpers::DocumentationHelpers
  include Pry::Helpers::BaseHelpers
  include Pry::Helpers::CommandHelpers
  include Pry::Helpers::Text
end
class Pry::ClassCommand < Pry::Command
end
class Pry::BlockCommand < Pry::Command
end
class Pry::NoCommandError < StandardError
end
class Pry::CommandSet
  include Enumerable
  include Pry::Helpers::BaseHelpers
end
class Pry::Result
end
class Pry::SyntaxHighlighter
end
class Pry::Editor
  include Pry::Helpers::CommandHelpers
end
class Pry::History
end
class Pry::ColorPrinter < PP
end
module Pry::ExceptionHandler
end
module Pry::SystemCommandHandler
end
module Pry::ControlDHandler
end
class Pry::CommandState
end
module Pry::Warning
end
module Pry::Env
end
class Pry::Command::Ls < Pry::ClassCommand
end
module Pry::Command::Ls::JRubyHacks
end
module Pry::Command::Ls::MethodsHelper
  include Pry::Command::Ls::JRubyHacks
end
module Pry::Command::Ls::Interrogatable
end
class Pry::Command::Ls::Grep
end
class Pry::Command::Ls::Formatter
end
class Pry::Command::Ls::Globals < Pry::Command::Ls::Formatter
end
class Pry::Command::Ls::Constants < Pry::Command::Ls::Formatter
  include Pry::Command::Ls::Interrogatable
end
class Pry::Command::Ls::Methods < Pry::Command::Ls::Formatter
  include Pry::Command::Ls::Interrogatable
  include Pry::Command::Ls::MethodsHelper
end
class Pry::Command::Ls::SelfMethods < Pry::Command::Ls::Formatter
  include Pry::Command::Ls::Interrogatable
  include Pry::Command::Ls::MethodsHelper
end
class Pry::Command::Ls::InstanceVars < Pry::Command::Ls::Formatter
  include Pry::Command::Ls::Interrogatable
end
class Pry::Command::Ls::LocalNames < Pry::Command::Ls::Formatter
end
class Pry::Command::Ls::LocalVars < Pry::Command::Ls::Formatter
end
class Pry::Command::Ls::LsEntity
end
class Pry::Config
  extend Pry::Config::Attributable
end
module Pry::Config::Attributable
end
class Pry::Config::Value
end
class Pry::Config::MemoizedValue
end
class Pry::Config::LazyValue
end
class Pry::Inspector
end
class Pry::Pager
end
class Pry::Pager::StopPaging < StandardError
end
class Pry::Pager::NullPager
end
class Pry::Pager::SimplePager < Pry::Pager::NullPager
end
class Pry::Pager::SystemPager < Pry::Pager::NullPager
end
class Pry::Pager::PageTracker
end
class Pry::Indent
  include Pry::Helpers::BaseHelpers
end
class Pry::Indent::UnparseableNestingError < StandardError
end
class Pry::ObjectPath
end
class Pry::Output
end
class Pry::InputLock
end
class Pry::InputLock::Interrupt < Exception
end
class Pry::REPL
  extend Pry::Forwardable
end
class Pry::Code
end
class Pry::Ring
end
class Pry::Method
  extend Pry::Forwardable
  extend Pry::Helpers::BaseHelpers
  include Pry::CodeObject::Helpers
  include Pry::Helpers::BaseHelpers
  include Pry::Helpers::DocumentationHelpers
end
class Pry::WrappedModule
  include Pry::CodeObject::Helpers
  include Pry::Helpers::BaseHelpers
end
class Pry::WrappedModule::Candidate
  extend Pry::Forwardable
  include Pry::CodeObject::Helpers
  include Pry::Helpers::DocumentationHelpers
end
class Pry::Slop
  include Enumerable
end
class Pry::Slop::Option
end
class Pry::Slop::Commands
  include Enumerable
end
class Pry::Slop::Error < StandardError
end
class Pry::Slop::MissingArgumentError < Pry::Slop::Error
end
class Pry::Slop::MissingOptionError < Pry::Slop::Error
end
class Pry::Slop::InvalidArgumentError < Pry::Slop::Error
end
class Pry::Slop::InvalidOptionError < Pry::Slop::Error
end
class Pry::Slop::InvalidCommandError < Pry::Slop::Error
end
class Pry::CLI
end
class Pry::CLI::NoOptionsError < StandardError
end
class Object < BasicObject
end
class BasicObject
end
class Pry::REPLFileLoader
end
class Pry::Code::LOC
end
class Pry::Code::CodeRange
end
class Pry::CodeFile
end
class Pry::Method::WeirdMethodLocator
end
class Pry::Method::Disowned < Pry::Method
end
class Pry::Method::Patcher
end
class Pry::Command::AmendLine < Pry::ClassCommand
end
class Pry::Command::Bang < Pry::ClassCommand
end
class Pry::Command::BangPry < Pry::ClassCommand
end
class Pry::Command::Cat < Pry::ClassCommand
end
class Pry::Command::Cat::AbstractFormatter
  include Pry::Helpers::BaseHelpers
  include Pry::Helpers::CommandHelpers
end
class Pry::Command::Cat::InputExpressionFormatter < Pry::Command::Cat::AbstractFormatter
end
class Pry::Command::Cat::ExceptionFormatter < Pry::Command::Cat::AbstractFormatter
  include Pry::Helpers::Text
end
class Pry::Command::Cat::FileFormatter < Pry::Command::Cat::AbstractFormatter
end
class Pry::Command::Cd < Pry::ClassCommand
end
class Pry::Command::ChangeInspector < Pry::ClassCommand
end
class Pry::Command::ChangePrompt < Pry::ClassCommand
end
class Pry::Command::ClearScreen < Pry::ClassCommand
end
class Pry::Command::CodeCollector
  include Pry::Helpers::CommandHelpers
end
class Pry::Command::DisablePry < Pry::ClassCommand
end
class Pry::Command::Edit < Pry::ClassCommand
end
class Pry::Command::Edit::ExceptionPatcher
end
module Pry::Command::Edit::FileAndLineLocator
end
class Pry::Command::Exit < Pry::ClassCommand
end
class Pry::Command::ExitAll < Pry::ClassCommand
end
class Pry::Command::ExitProgram < Pry::ClassCommand
end
class Pry::Command::FindMethod < Pry::ClassCommand
  extend Pry::Helpers::BaseHelpers
end
class Pry::Command::FixIndent < Pry::ClassCommand
end
class Pry::Command::Help < Pry::ClassCommand
end
class Pry::Command::Hist < Pry::ClassCommand
end
class Pry::Command::ImportSet < Pry::ClassCommand
end
class Pry::Command::JumpTo < Pry::ClassCommand
end
class Pry::Command::ListInspectors < Pry::ClassCommand
end
class Pry::Command::Nesting < Pry::ClassCommand
end
class Pry::Command::Play < Pry::ClassCommand
end
class Pry::Command::PryBacktrace < Pry::ClassCommand
end
class Pry::Command::Version < Pry::ClassCommand
end
class Pry::Command::RaiseUp < Pry::ClassCommand
end
class Pry::Command::ReloadCode < Pry::ClassCommand
end
class Pry::Command::Reset < Pry::ClassCommand
end
class Pry::Command::Ri < Pry::ClassCommand
end
class Pry::Command::SaveFile < Pry::ClassCommand
end
class Pry::Command::ShellCommand < Pry::ClassCommand
end
class Pry::Command::ShellMode < Pry::ClassCommand
end
class Pry::Command::ShowInfo < Pry::ClassCommand
  extend Pry::Helpers::BaseHelpers
end
class Pry::Command::ShowDoc < Pry::Command::ShowInfo
  include Pry::Helpers::DocumentationHelpers
end
class Pry::Command::ShowInput < Pry::ClassCommand
end
class Pry::Command::ShowSource < Pry::Command::ShowInfo
  include Pry::Helpers::DocumentationHelpers
end
class Pry::Command::Stat < Pry::ClassCommand
end
class Pry::Command::SwitchTo < Pry::ClassCommand
end
class Pry::Command::ToggleColor < Pry::ClassCommand
end
class Pry::Command::WatchExpression < Pry::ClassCommand
end
class Pry::Command::WatchExpression::Expression
end
class Pry::Command::Whereami < Pry::ClassCommand
end
class Pry::Command::Wtf < Pry::ClassCommand
end
