# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rainbow/all/rainbow.rbi
#
# rainbow-3.1.1

module Rainbow
end
class Rainbow::StringUtils
end
module Rainbow::X11ColorNames
end
class Rainbow::Color
end
class Rainbow::Color::Indexed < Rainbow::Color
end
class Rainbow::Color::Named < Rainbow::Color::Indexed
end
class Rainbow::Color::RGB < Rainbow::Color::Indexed
end
class Rainbow::Color::X11Named < Rainbow::Color::RGB
  include Rainbow::X11ColorNames
end
class Rainbow::Presenter < String
end
class Rainbow::NullPresenter < String
end
class Rainbow::Wrapper
end
