# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tailwindcss-rails-2.0.8-arm64/all/tailwindcss-rails-2.0.8-arm64.rbi
#
# tailwindcss-rails-2.0.8-arm64-darwin

module Tailwindcss
end
module Tailwindcss::Upstream
end
class Tailwindcss::Engine < Rails::Engine
end
