# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/temple/all/temple.rbi
#
# temple-0.8.2

module Temple
end
module Temple::Mixins
end
module Temple::ERB
end
module Temple::Generators
end
module Temple::Filters
end
module Temple::HTML
end
module Temple::Utils
  extend Temple::Utils
end
module Temple::Mixins::ClassOptions
end
module Temple::Mixins::ThreadOptions
end
module Temple::Mixins::Options
end
class Temple::Parser
  extend Temple::Mixins::ClassOptions
  extend Temple::Mixins::ThreadOptions
  include Temple::Mixins::Options
  include Temple::Utils
end
class Temple::ImmutableMap
  include Enumerable
end
class Temple::MutableMap < Temple::ImmutableMap
end
class Temple::OptionMap < Temple::MutableMap
end
module Temple::Mixins::CoreDispatcher
end
module Temple::Mixins::EscapeDispatcher
end
module Temple::Mixins::ControlFlowDispatcher
end
module Temple::Mixins::CompiledDispatcher
end
class Temple::Mixins::CompiledDispatcher::DispatchNode < Hash
end
module Temple::Mixins::Dispatcher
  include Temple::Mixins::CompiledDispatcher
  include Temple::Mixins::ControlFlowDispatcher
  include Temple::Mixins::CoreDispatcher
  include Temple::Mixins::EscapeDispatcher
end
class Temple::Filter
  extend Temple::Mixins::ClassOptions
  extend Temple::Mixins::ThreadOptions
  include Temple::Mixins::Dispatcher
  include Temple::Mixins::Options
  include Temple::Utils
end
module Temple::HTML::Dispatcher
end
class Temple::HTML::Filter < Temple::Filter
  include Temple::HTML::Dispatcher
end
module Temple::Mixins::EngineDSL
end
class Temple::Engine
  extend Temple::Mixins::ClassOptions
  extend Temple::Mixins::EngineDSL
  extend Temple::Mixins::ThreadOptions
  include Temple::Mixins::EngineDSL
  include Temple::Mixins::Options
end
class Temple::Generator
  extend Temple::Mixins::ClassOptions
  extend Temple::Mixins::ThreadOptions
  include Temple::Mixins::CompiledDispatcher
  include Temple::Mixins::Options
  include Temple::Utils
end
class Temple::Generators::Array < Temple::Generator
end
class Temple::Generators::ArrayBuffer < Temple::Generators::Array
end
class Temple::Generators::StringBuffer < Temple::Generators::ArrayBuffer
end
class Temple::Filters::Encoding < Temple::Parser
end
class Temple::Filters::RemoveBOM < Temple::Parser
end
class Temple::HTML::AttributeSorter < Temple::HTML::Filter
end
class Temple::HTML::AttributeMerger < Temple::HTML::Filter
end
class Temple::HTML::Fast < Temple::HTML::Filter
end
class Temple::HTML::Pretty < Temple::HTML::Fast
end
class Temple::Filters::Escapable < Temple::Filter
end
class Temple::Filters::ControlFlow < Temple::Filter
end
class Temple::Filters::MultiFlattener < Temple::Filter
end
class Temple::Filters::StaticMerger < Temple::Filter
end
module Temple::Templates
end
module Temple::Mixins::Template
  include Temple::Mixins::ClassOptions
end
class Temple::Templates::Tilt < Tilt::Template
  extend Temple::Mixins::Template
end
class Temple::Generators::RailsOutputBuffer < Temple::Generators::StringBuffer
end
class Temple::Templates::Rails
  extend Temple::Mixins::Template
end
