require:
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "tmp/**/*"
    - "config/**/*"
    - "db/**/*"
    - "lib/**/*"
    - "node_modules/**/*"
    - "spec/**/*"
    - 'vendor/**/*'
    - '*.md'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

Style/Documentation:
  Enabled: false

Sorbet/FalseSigil:
  Exclude:
    - "app/helpers/application_helper.rb"
    - "app/models/concerns/inquirer.rb"

Sorbet/ValidSigil:
  Exclude:
    - "app/helpers/application_helper.rb"
    - "app/models/concerns/inquirer.rb"
