require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '*.md'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/**/*_policy_spec.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Naming/BlockForwarding:
  Enabled: false
