# https://github.com/ondrejbartas/sidekiq-cron
# use https://crontab.guru/ to validate
# validations for this file exist in /spec/configs/schedule_spec.rb

# Every hour
trigger_hourly_job:
  cron: '0 * * * *'
  class: 'Clock::HourlyTick'
  queue: scheduled_jobs

# Every day
trigger_daily_job:
  cron: '0 0 * * *'
  daily: 'Clock::DailyTick'
  queue: scheduled_jobs
