name: Continuous integration
on: push
env:
  DATABASE_URL: postgresql://rails_github_actions:postgres@localhost:5432/changepack_test
  RAILS_ENV: test
  CI: true
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: rails_github_actions
          POSTGRES_DB: changepack_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run RuboCop
        run: bundle exec rubocop
      - name: Run Brakeman
        run: bundle exec brakeman
      - name: Run slim-lint
        run: bundle exec slim-lint app/views
      - name: Setup test database
        run: rails db:create db:migrate
      - name: Run RSpec
        run: bundle exec rspec
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        env:
          CYPRESS: true
        with:
          start: bundle exec rails server -e test -p 5017
          wait-on: 'http://localhost:5017'
          browser: chrome
          headless: true
          project: ./spec
          config-file: cypress.config.js
